### ISSUE TITLE
Dict order in memory and on disk differs

### ISSUE THREAD

**Issue by L4rS6** [jcstroud/pyfscache#6]
If I run the script below I get differ orders from my_dict:

```
{'a': 'a', 'one': 1, 'three': 3, 'two': 2}
its in cache => updated it
BEFORE:
{'a': 'a', 'three': 3, 'two': 2, 'one': 1}
AFTER:
{'a': 'a', 'one': 1, 'three': 3, 'two': 2}
NON CACHE:
{'a': 'a', 'three': 3, 'two': 2, 'one': 1}
```

In my opinion the dict order after AFTER and BEFORE should be same, because update_item updates the disk and memory.

And that's the script

```
import pyfscache

cache = pyfscache.FSCache("/root/mycache", minutes=90)

my_dict=dict(one=1,two=2,three=3,a='a')
id="me"

pillar_cache.clear()

if id in pillar_cache:
        print cache[id]
        print "its in cache => updated it"
        cache.update_item(id, my_dict)
        print "BEFORE:\n%s" % cache[id]
        pillar_cache.clear()
        print "AFTER:\n%s" % cache[id]
else:
        print "not in cache => add it"
        cache[id] = my_dict
print "NON CACHE:\n%s" % my_dict
```

Thank you.

**Comment by tomderuijter** [comment]
That's a Python issue, not of this package. The order of dictionary keys is
determined at runtime. Use an OrderedDict if you want to guarantee ordering.

If I run the script below I get differ orders from my_dict:

{'a': 'a', 'one': 1, 'three': 3, 'two': 2}
its in cache => updated it
BEFORE:
{'a': 'a', 'three': 3, 'two': 2, 'one': 1}
AFTER:
{'a': 'a', 'one': 1, 'three': 3, 'two': 2}
NON CACHE:
{'a': 'a', 'three': 3, 'two': 2, 'one': 1}

In my opinion the dict order after AFTER and BEFORE should be same, because
update_item updates the disk and memory.

And that's the script

import pyfscache

cache = pyfscache.FSCache("/root/mycache", minutes=90)

my_dict=dict(one=1,two=2,three=3,a='a')
id="me"

pillar_cache.clear()

if id in pillar_cache:
        print cache[id]
        print "its in cache => updated it"
        cache.update_item(id, my_dict)
        print "BEFORE:\n%s" % cache[id]
        pillar_cache.clear()
        print "AFTER:\n%s" % cache[id]
else:
        print "not in cache => add it"
        cache[id] = my_dict
print "NON CACHE:\n%s" % my_dict

Thank you.

—
Reply to this email directly or view it on GitHub
https://github.com/jcstroud/pyfscache/issues/6.

**Comment by L4rS6** [comment]
@tomderuijter Thank you for the explanation and your quick reply!
